### PR TITLE
Create RakNetPacket.java

### PR DESCRIPTION
**Pull request by alejzeis**
Separate interface's for RakNet packets and Minecraft packets.

### CODE REVIEW

**Comment by PEMapModder** [comment]
I'll merge it if you add more actual code :)

**Comment by alejzeis** [comment]
I will when I can.

On Friday, July 25, 2014, PEMapModder notifications@github.com wrote:

> I'll merge it if you add more actual code :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LegendOfMCPE/FakeClient/pull/2#issuecomment-50218909.

##

**Comment by PEMapModder** [comment]
We're renaming the project to PocketBot.

**Comment by PEMapModder** [comment]
Also, why aren't the methods public visibility?

**Comment by alejzeis** [comment]
Revived? Lol you should check out NeptuneClient.

On Saturday, September 13, 2014, PEMapModder notifications@github.com
wrote:

> Also, why aren't the methods public visibility?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/LegendOfMCPE/PocketBot/pull/2#issuecomment-55482521.

##

**Comment by PEMapModder** [comment]
Revived?

**Comment by alejzeis** [comment]
Which methods?

**Pull request closed without merging**
